### ISSUE TITLE
AddCharModel crashes the server

### ISSUE THREAD

**Issue by kchmie** [kodeyeen/omp#3]
I have the following code:
```go
omp.Events.Listen(omp.EventTypeGameModeInit, func(e *omp.GameModeInitEvent) bool {
  omp.AddCharModel(104, 20001, "beta_skins/fam12.dff", "beta_skins/fam12.txd")
  omp.AddCharModel(294, 20002, "postal_dude/dude.dff", "postal_dude/dude.txd")
  return true
})
```

It appears `omp.AddCharModel` outright crashes the server without yielding any message. I've tried with multiple parameters and models and it always is like that. What's interesting, the server doesn't even produce any dump file as it usually does when crashing.

`artwork.enable` is true. Running windows.

**Comment by kodeyeen** [comment]
f

**Comment by hexxfy** [comment]
Fixed.
